ccflags-y := -Ofast -fgcse-lm -fgcse-sm -fsched-spec-load -fforce-addr -ffast-math -fsingle-precision-constant -marm -mtune=cortex-a7 -mfpu=neon-vfpv4 -ftree-vectorize

obj-y += msm_ion.o ion_cp_common.o
